# Generated by Django 5.2.3 on 2025-07-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0014_farm_created_at_farm_owner_farm_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='resolved_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
