# Generated by Django 5.2.3 on 2025-07-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0015_alert_resolved_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_notifications',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sms_notifications',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(choices=[('farm_owner', 'Farm Owner')], default='farm_owner', max_length=20),
        ),
    ]
