# Generated by Django 5.2.3 on 2025-07-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0016_remove_customuser_email_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, help_text='Enter your full name.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(default='farm_owner', max_length=20),
        ),
    ]
