# Generated by Django 5.2.3 on 2025-07-04 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0018_farm_primary_plant_type_alter_customuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmsection',
            name='primary_plant_typeplant_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='web_app.planttype'),
        ),
        migrations.AlterField(
            model_name='farmsection',
            name='plant_type',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
    ]
