# Generated by Django 5.2.3 on 2025-07-04 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0019_farmsection_primary_plant_typeplant_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planttype',
            name='is_global',
            field=models.BooleanField(default=False, help_text='Indicates if this is a system-wide or global plant type.'),
        ),
        migrations.AddField(
            model_name='planttype',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The user who created this plant type. Null for global/system-defined types.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_plant_types', to=settings.AUTH_USER_MODEL),
        ),
    ]
