# Generated by Django 5.2.3 on 2025-07-04 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0020_planttype_is_global_planttype_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='primary_plant_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farms_with_this_primary_type', to='web_app.planttype'),
        ),
    ]
